# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rej2Qc392cgMK6G5IePr47Yzt4cULkTy
"""

import streamlit as st
from openai import OpenAI

client = OpenAI()

st.title("MBTI 聊天預測")

user_input = st.text_input("請輸入你的問題或聊天內容：")

if user_input:
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "你是一個可以判斷使用者 MBTI 類型的聊天助手。"},
            {"role": "user", "content": user_input}
        ]
    )
    st.write("模型回覆：")
    st.write(response.choices[0].message.content)
