# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rej2Qc392cgMK6G5IePr47Yzt4cULkTy
"""

import streamlit as st
import openai

st.set_page_config(page_title="MBTI 聊天分析器", page_icon="🧠")

# 讀取 OpenAI API 金鑰（部署時建議用 secrets）
openai.api_key = st.secrets["OPENAI_API_KEY"]

st.title("🧠 MBTI 聊天分析器")
st.markdown("和我聊聊，我將根據你的回答預測你的 MBTI 類型！")

# 初始化對話
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "system", "content": "你是一位擅長人格判斷的心理師，會根據使用者的回答逐步預測其 MBTI 類型。請以自然聊天方式互動，避免直接給出結果。"}
    ]

# 顯示歷史聊天紀錄
for msg in st.session_state.messages[1:]:
    st.chat_message(msg["role"]).write(msg["content"])

# 使用者輸入
if user_input := st.chat_input("輸入訊息開始聊天..."):
    st.chat_message("user").write(user_input)
    st.session_state.messages.append({"role": "user", "content": user_input})

    # 呼叫 GPT API
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=st.session_state.messages
    )

    reply = response.choices[0].message.content
    st.chat_message("assistant").write(reply)
    st.session_state.messages.append({"role": "assistant", "content": reply})